modLoader="javafml" 
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]]
modId="herebedragons"
version="0.1"
displayName="Here Be Dragons"
authors="BudgieGryphon"
description='''
A Minecraft mod centered around adventure, combat, and dragons.
'''

[[dependencies.herebedragons]]
    modId="forge" 
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.herebedragons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

